import "atropos/css";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import FooterPg from "@/components/layout/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} overflow-x-hidden`}>
        <Header />
        {children}
        <FooterPg />
      </body>
    </html>
  );
}
